version = 0.1

[default.build.parameters]
beta_features = true
parallel = true
[default.sync.parameters]
beta_features = true


[default.deploy.parameters]
stack_name = "eziPolls"
resolve_s3 = true
s3_prefix = "eziPolls"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
[prod]
[prod.sync]
[prod.sync.parameters]
watch = false